# Generated by Django 4.2.17 on 2025-09-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0039_auto_20220506_0833"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadparallelismlimit",
            name="max_number",
            field=models.PositiveSmallIntegerField(
                default=5, help_text="The maximum number of parallel uploads (0 to 32767)."
            ),
        ),
    ]
